### PR TITLE
Fixed minor issues with MMOL/L settings.

### PR DESCRIPTION
**Pull request by sgmoore**

### CODE REVIEW

**Comment by Delubear** [comment]
Can you increase the patch number in the appsettings.json version?

**Comment by sgmoore** [comment]
> Can you increase the patch number in the appsettings.json version?

Done, and sorry. (You did warn me about that before!)

**Comment by Delubear** [comment]
> > Can you increase the patch number in the appsettings.json version?
> 
> Done, and sorry. (You did warn me about that before!)


Also really want to thank you for the PRs and fixes you've found.

**Comment by sgmoore** [comment]
Glad to help.

By the way, this is the first project where I have submitted more than than one or two prs, so if I am doing anything wrong, don't hesitate to tell me, whether I am missing some conventions, breaking some coding style or even if the code isn't up to scratch.

I have a pretty thick skin and won't get offended easily, even if you reject any of my prs.

**Pull request merged**
